name: tem_tools
channels:
    - conda-forge
    - defaults
    - gimli
dependencies:
    - pygimli = 1.5.2
    - empymod = 2.4.0
    - ipython = 8.28.0
    - obspy = 1.4.1  
    - pandas = 2.2.3
    - ipywidgets
    - pyproj